name       : qt6-webchannel
version    : 6.2.2
release    : 2
source     :
    - https://download.qt.io/official_releases/qt/6.2/6.2.2/submodules/qtwebchannel-everywhere-src-6.2.2.tar.xz : 32e3d74a89cc0ad40e08c93f8c1ce7261777fef3235f3192abbf79f7874bf845
license    :
    - GFDL-1.3-or-later
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt6 Webchannel Module
description: |
    The Qt WebChannel module offers Qt applications a seamless way to publish QObjects for interaction with HTML/JavaScript clients. These clients can either be inside local Qt WebViews or any other, potentially remote, client which supports JavaScript, as long as a communication channel such as WebSocket is available.

    Qt WebChannel uses introspection on the QObjects and sends this serialized data to the clients. There, with the help of a small JavaScript library, an object is created which simulates the API of the QObject. Any invokable methods, including slots, can be called as well as properties read and written. Additionally you can connect to signals and register JavaScript callbacks as handlers.
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6WebSockets)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
